# Generated by Django 4.2.20 on 2025-03-08 03:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('pages', models.IntegerField(blank=True)),
                ('release', models.DateField(blank=True)),
                ('validate', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(100)])),
                ('comment', models.CharField(blank=True, max_length=300)),
                ('status', models.IntegerField(choices=[(0, 'Read'), (1, 'Reading'), (2, 'Drop'), (3, 'List')])),
                ('bookId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(fields=('name', 'author'), name='unique_book', violation_error_message='This book has already been registered'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('userId', 'bookId'), name='unique_user_review_per_book', violation_error_message='User has already made a review for this book'),
        ),
    ]
